### ISSUE TITLE
Serious issues!!piston invisible.

### ISSUE THREAD

**Issue by le10077** [Arckenver/Nations#155] opened 2017-07-21 09:42 UTC
Players who no build permission triggers the piston and the piston is invisible!!!
Reposition the piston will fail!!!

**Comment by yepidoodles** [comment] 2017-07-21 09:48
I've seen this on my servers too, use world edit to remove the invisible blocks.

**Comment by TheoKah** [comment] 2017-07-22 13:26
This is new.
What version of sponge are you on?

**Comment by le10077** [comment] 2017-07-22 19:56
@TheoKah The last version. spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar and Nations-2.5.jar

**Comment by CamGenius** [comment] 2017-10-03 22:57
I have this issue too

**Comment by pyscho974** [comment] 2017-10-14 18:14
this is still an issue.   had it happen repeatedly with 10 pistons :)

**Comment by TheoKah** [comment] 2017-10-14 18:57
Can you give me the version of sponge and nations you are on?
Also can you give me the process to reproduce the bug?

**Comment by CamGenius** [comment] 2017-10-14 22:40
Sponge Version: spongeforge-1.11.2-2476-6.1.0-BETA-2652
Nations Version: Nations-2.8-S6.1-MC1.11.2
Forge Version: forge-1.11.2-13.20.1.2386-universal

Steps to Reproduce Bug:
1) Create a nation with claims under one user.
2) Put a sticky piston with block on it then add a pressure plate to activate it.
3) With another user not in the nation with build rights disallowed and interactions allowed.
4) Go use the unprivileged user to step on the pressure plate.
5) The piston disappears with also creating a block that nothing can be placed in.

P.S. I think the issue is that a user without build rights is moving a block by using his/her interaction rights. In result this creates a bug.

**Comment by pyscho974** [comment] 2017-10-14 22:45
spongeforge-1.10.2-2477-5.2.0-BETA-2691
Nations-2.9-S5.1-MC1.10.2-hotfix_windows
forge 2477

mostly same  as previous post but newer versions of sponge and nations

**Comment by CamGenius** [comment] 2017-10-14 22:51
It says that 2.9 is a hotfix does that mean it is still stable? I am worried about using an unstable version on my server. On the other hand it says that it fixed the piston issue but the post above says that it didn't.

**Comment by TheoKah** [comment] 2017-10-14 23:26
The problem is fixed since v2.9, you are still on v2.8

hotfix-windows doen't have the piston fix.

use this version: https://github.com/Arckenver/Nations/releases/tag/v2.9
This has the windows fix and the piston fix

The 'hotfix1' is safe to use. I have it running for 1 week on 9 live servers

**Comment by CamGenius** [comment] 2017-10-14 23:31
Is it stable because it says hotfix?

**Comment by pyscho974** [comment] 2017-10-15 00:20
oh.. thought when u did the hotfix it was on the latest version :) since hotfix was for the folder name issue

**Comment by CamGenius** [comment] 2017-10-15 00:23
Thanks for getting this fixed. Now the players on my server can create piston enabled traps.

**Comment by CamGenius** [comment] 2017-10-15 00:25
I would suggest marking this issue as closed also.

**Comment by Arckenver** [comment] 2024-12-29 20:30
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.

**Closed as completed by Arckenver** 2024-12-29 20:30 UTC
