### ISSUE TITLE
idea for claimed areas

### ISSUE THREAD

**Issue by Sitherious** [Arckenver/Nations#74] opened 2016-12-29 14:33 UTC
if this is already a feature , sorry but is there a way to show or display claimed areas or an outline of the claim visually.

**Comment by ProsperCraft** [comment] 2017-01-09 16:48
Already requested this in October - https://github.com/Arckenver/Nations/issues/39

**Comment by TheoKah** [comment] 2017-01-10 22:45
Duplicate of #39

**Closed as completed by TheoKah** 2017-01-10 22:45 UTC
