### ISSUE TITLE
Suggestion: use option

### ISSUE THREAD

**Issue by 5igm** [Arckenver/Nations#24] opened 2016-08-16 09:38 UTC
After I set citizen and outsiders as true, citizen and outsiders still cannot open chest. I suggest to add a new option chest or add open-chest function into use option.

**Comment by Arckenver** [comment] 2016-08-16 11:15
That is not supposed to happen. Did you enable the `INTERACT` permission in nation for `citizens` and `outsiders` ?

**Comment by 5igm** [comment] 2016-08-16 14:06
Yes, I have. I hope there can be an option to enable players using container. @Arckenver

**Comment by Arckenver** [comment] 2016-08-16 14:16
What is the message when trying to open it ? Is it a message from Nations ? If so, what is the LanguageHandler message id (AA, AB, AC etc) ?

**Comment by 5igm** [comment] 2016-08-16 14:36
When I setted permission INTERACT as true to outsider, there was no more message from console. It just showed the command.

**Comment by Arckenver** [comment] 2016-08-16 14:47
Yeah but when an outsider tries to open a chest, what does it say ?

**Comment by 5igm** [comment] 2016-08-16 15:13
My fault. It seems container is synchronous with interact perm. 
The message is HI

**Comment by Arckenver** [comment] 2016-08-17 14:12
What do you mean by "container is synchronous with interact perm" ?

I'd need more information, is where you are trying to open a chest as an outsider a zone inside the nation or just in the nation ? Is it an admin nation ? etc.

**Comment by 5igm** [comment] 2016-08-17 14:38
As a outsider. In a nation not a zone. It is a player nation.
If I set use as true, players can use chest in the nation.
In the opposite, players cannot use chest in the nation.

**Comment by Arckenver** [comment] 2016-08-17 15:11
I don't quite understand the problem here. Could you please reformulate using the following official terminology ?

### Player types
- `citizen` - member of the nation
- `outsider` - player that is not in a given nation

### Permission types
- `build` - ability to place/break blocks
- `interact` - ability to open chests, switch buttons, open doors etc

**Comment by 5igm** [comment] 2016-08-17 17:21
Sorry.

> My fault. It seems container is synchronous with interact perm. 
> The message is HI

As the message I left above, I report an error mistakely. It isn't an error. I am aplogized for my fault. Thanks for your help and effort. It is not a real error. I test it again, and now nation work well at this part this time. I think I made a mistake. Sorry for my wrong error report.

**Comment by Arckenver** [comment] 2016-08-17 17:50
No problem ! I didn't understand so it's also my fault. Issues are also there so you can get advice even if your problem doesn't come directly form a bug in Nations.

Thankfully the problem is fixed now :wink:

**Closed as completed by Arckenver** 2016-08-17 17:50 UTC
Labels: error
