### ISSUE TITLE
Addrect Startup Crash

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#70] opened 2016-12-12 15:49 UTC
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2123-6.0.0-BETA-1902.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 12/11/16 11:24 PM
Description: Watching Server

java.lang.Error
	at com.arckenver.nations.object.Region.addRect(Region.java:59)
	at com.arckenver.nations.serializer.NationDeserializer.deserialize(NationDeserializer.java:52)
	at com.arckenver.nations.serializer.NationDeserializer.deserialize(NationDeserializer.java:21)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at com.arckenver.nations.DataHandler.load(DataHandler.java:68)
	at com.arckenver.nations.NationsPlugin.onStart(NationsPlugin.java:136)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_NationsPlugin_onStart22.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:398)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:53)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:858)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at com.arckenver.nations.object.Region.addRect(Region.java:59)
	at com.arckenver.nations.serializer.NationDeserializer.deserialize(NationDeserializer.java:52)
	at com.arckenver.nations.serializer.NationDeserializer.deserialize(NationDeserializer.java:21)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at com.arckenver.nations.DataHandler.load(DataHandler.java:68)
	at com.arckenver.nations.NationsPlugin.onStart(NationsPlugin.java:136)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_NationsPlugin_onStart22.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:398)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:53)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:858)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297)

-- Thread Dump --
Details:
	Threads: "Server Watchdog" Id=79 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:46)
	at java.lang.Thread.run(Thread.java:745)


"Query Listener #1" Id=78 RUNNABLE
	at java.net.PlainDatagramSocketImpl.peekData(Native Method)
	-  locked java.net.PlainDatagramSocketImpl@7d2c1b59
	at java.net.DatagramSocket.receive(DatagramSocket.java:743)
	-  locked java.net.DatagramPacket@73ebfa8c
	-  locked java.net.DatagramSocket@4b444f94
	at net.minecraft.network.rcon.RConThreadQuery.run(SourceFile:268)
	at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #3" Id=46 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)


"pool-3-thread-4" Id=77 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...


"Netty Epoll Server IO #2" Id=45 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)


"Timer-1" Id=76 TIMED_WAITING on java.util.TaskQueue@32d6f0b7
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@32d6f0b7
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)


"pool-3-thread-3" Id=75 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...


"MVStore background writer nio:/home/mch/multicraft/servers/server16500/config/pjp/data.mv.db" Id=73 TIMED_WAITING on java.lang.Object@2fbdd367
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@2fbdd367
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2708)


"HikariPool-2 housekeeper" Id=70 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3ae6386
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3ae6386
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...


"Netty Epoll Server IO #1" Id=44 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #0" Id=43 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)


"H2 Log Writer PIXELMON2" Id=41 TIMED_WAITING on org.h2.store.WriterThread@572f1ee2
	at java.lang.Object.wait(Native Method)
	-  waiting on org.h2.store.WriterThread@572f1ee2
	at org.h2.store.WriterThread.run(WriterThread.java:102)
	at java.lang.Thread.run(Thread.java:745)


"pool-3-thread-2" Id=40 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...


"Okio Watchdog" Id=38 WAITING on java.lang.Class@52f90ff8
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Class@52f90ff8
	at java.lang.Object.wait(Object.java:502)
	at net.buycraft.plugin.internal.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:338)
	at net.buycraft.plugin.internal.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)


"OkHttp ConnectionPool" Id=37 TIMED_WAITING on net.buycraft.plugin.internal.okhttp3.ConnectionPool@139ed82b
	at java.lang.Object.wait(Native Method)
	-  waiting on net.buycraft.plugin.internal.okhttp3.ConnectionPool@139ed82b
	at java.lang.Object.wait(Object.java:460)
	at net.buycraft.plugin.internal.okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@6b728c6b


"pool-3-thread-1" Id=36 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@77d47029
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...


"MVStore background writer nio:/home/mch/multicraft/servers/server16500/config/flexiblelogin/database.mv.db" Id=33 TIMED_WAITING on java.lang.Object@63dc2b8d
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@63dc2b8d
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2708)


"HikariPool-1 housekeeper" Id=30 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4c2bf11a
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4c2bf11a
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...


"Sponge Async Scheduler Thread" Id=26 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@56b7b1a8
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@56b7b1a8
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.spongepowered.common.scheduler.AsyncScheduler.preTick(AsyncScheduler.java:112)
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:102)
	at org.spongepowered.common.scheduler.AsyncScheduler.mainLoop(AsyncScheduler.java:66)
	at org.spongepowered.common.scheduler.AsyncScheduler$$Lambda$318/631827574.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


"Timer-0" Id=23 TIMED_WAITING on java.util.TaskQueue@338d64d5
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@338d64d5
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)


"process reaper" Id=21 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@318fa16a
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@318fa16a
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...


"DestroyJavaVM" Id=19 RUNNABLE


"Server console handler" Id=17 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	-  locked java.io.BufferedInputStream@223f3560
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	-  locked java.io.InputStreamReader@49eeea7e
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	...


"Server thread" Id=16 RUNNABLE
	at com.arckenver.nations.object.Region.addRect(Region.java:59)
	at com.arckenver.nations.serializer.NationDeserializer.deserialize(NationDeserializer.java:52)
	at com.arckenver.nations.serializer.NationDeserializer.deserialize(NationDeserializer.java:21)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	...


"Server Infinisleeper" Id=15 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:78)


"Snooper Timer" Id=14 WAITING on java.util.TaskQueue@69a491d
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@69a491d
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)


"Signal Dispatcher" Id=5 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@3819feaa
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3819feaa
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@45db82a7
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@45db82a7
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)



Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:63)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5547107560 bytes (5290 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -Xmx8192M -Xms8192M -XX:+UseG1GC -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (custom.jar) 
	UCHIJAAAA	Forge{12.18.2.2151} [Minecraft Forge] (custom.jar) 
	UCHIJAAAA	spongeapi{6.0.0-SNAPSHOT-24eb858} [SpongeAPI] (spongeforge-1.10.2-2123-6.0.0-BETA-1902.jar) 
	UCHIJAAA	sponge{1.10.2-2123-6.0.0-BETA-1902} [SpongeForge] (spongeforge-1.10.2-2123-6.0.0-BETA-1902.jar) 
	UCHIJAAA	nucleus-mixin{0.15.0-5.0} [Nucleus Mixins] (NucleusMixins-0.15.0-S5-mixinplugin.jar) 
	UCHIJAAA	actionbroadcaster{0.4.4} [ActionBroadcaster] (ActionBroadcaster.jar) 
	UCHIJAAA	adminshop{1.8.2} [AdminShop] (AdminShop-1.10.2-1.8.2-universal.jar) 
	UCHIJAAA	autobroadcaster{0.2.0} [AutoBroadcaster] (AutoBroadcaster-0.2.0.jar) 
	UCHIJAAA	buycraft{SET_BY_MAGIC} [Buycraft] (BuycraftX (4).jar) 
	UCHIJAAA	economylite{2.6.0} [EconomyLite] (EconomyLite-5.0.0-2.6.0.jar) 
	UCHIJAAA	flexiblelogin{0.8} [FlexibleLogin] (FlexibleLogin (6).jar) 
	UCHIJAAA	keys{1.2} [keys] (Keys-1.2.1-5-g751445c.jar) 
	UCHIJAAA	nations{2.1} [Nations] (Nations-2.1.jar) 
	UCHIJAAA	nofalldamage{1.0.0} [NoFallDamage] (NoFallDamage-1.0-SNAPSHOT (1).jar) 
	UCHIJAAA	nucleus{0.16.2-5.0} [Nucleus] (Nucleus-0.16.1-S5-1.10.2-plugin.jar) 
	UCHIJAAA	nuvotifier{2.3.3} [NuVotifier] (nuvotifier-universal-2.3.3.jar) 
	UCHIJAAA	permissionsex{2.0-SNAPSHOT-b145} [PermissionsEx] (PermissionsEx-Sponge (3).jar) 
	UCHIJAAA	pixelauction{1.1.1} [Pixel Auction] (PixelAuction-1.10.2-1.1.1-universal.jar) 
	UCHIJAAA	pixelmon{5.0.0-beta12} [Pixelmon] (Pixelmon-1.10.2-5.0.0-beta12-universal.jar) 
	UCHIJAAA	pixelextras{2.2.3} [Pixel Extras] (PixelExtras-1.10.2-2.2.3-universal.jar) 
	UCHIJAAA	pjp{0.13.4} [ProjectPortals] (projectportals-5.1.0-0.13.4.jar) 
	UCHIJAAA	pjw{0.11.2} [ProjectWorlds] (projectworlds-5.1.0-0.11.2.jar) 
	UCHIJAAA	redprotect{6.5.1} [RedProtect] (RedProtect-Sponge-6.5.1-b220.jar) 
	UCHIJAAA	votifierlistener{0.6.4} [VotifierListener] (SimpleVotifierListener-0.6.4.jar) 
	UCHIJAAA	skinsrestorer{1.0} [SkinsRestorer] (SkinsRestorer-v12.8.4.jar) 
	UCHIJAAA	spongycord{1.1.0} [SpongyCord] (SpongyCord-1.1.0.jar) 
	UCHIJAAA	wondertrade{4.4.4} [Wondertrade] (WonderTrade-1.10.2-4.4.4-universal.jar) 
	UCHIJAAA	worldedit{6.1.5-SNAPSHOT} [WorldEdit] (worldedit-sponge-mc1.10.2-6.1.5-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2123-6.0.0-BETA-1902.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 96; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)](url)
```

**Comment by TheoKah** [comment] 2016-12-19 20:16
There is a problem within at least one of the nation save file

In order to find out which one, you can try the following:
- move all files from the config/nations/nations folder in a safe place
- start the server, no nation should exist
- copy the files back to config/nations/nations one by one and use /na reload after each copy
when server crash this mean the last file you moved is the faulty one and you can try to open it and fix it.

if you have a lot of nations, you can copy them like 10 by 10 to try and locate it faster

**Comment by GershonR** [comment] 2016-12-20 23:31
Is it possible to prevent the save file from corrupting?

**Comment by TheoKah** [comment] 2016-12-21 01:10
If you can locate the buggy nation save, post it here.
I'll try and see what part is bugged and if if rings a bell...

Still it is possible for this to be caused by a server crash when the file were written or something not related to nations..

**Comment by TheoKah** [comment] 2017-01-10 22:54
Closing this issue. My offer about trying to debug the nation's file if you find the buggy one(s) still stands.

**Closed as completed by TheoKah** 2017-01-10 22:54 UTC

**Comment by GershonR** [comment] 2017-01-11 00:23
I think it happens just very rarely, I have over 50 nation files so it will take a long time to find which one it is.
