### ISSUE TITLE
Piston Crash

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#65] opened 2016-11-27 05:01 UTC
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2123-5.1.0-BETA-1911.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 11/26/16 11:58 PM
Description: Watching Server

java.lang.Error
	at com.arckenver.nations.DataHandler.getNation(DataHandler.java:140)
	at com.arckenver.nations.DataHandler.getPerm(DataHandler.java:207)
	at com.arckenver.nations.listener.BuildPermListener.lambda$null$59(BuildPermListener.java:31)
	at com.arckenver.nations.listener.BuildPermListener$$Lambda$1020/1869006253.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.arckenver.nations.listener.BuildPermListener.lambda$onPlayerPlacesBlock$60(BuildPermListener.java:30)
	at com.arckenver.nations.listener.BuildPermListener$$Lambda$1019/611640378.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.arckenver.nations.listener.BuildPermListener.onPlayerPlacesBlock(BuildPermListener.java:30)
	at org.spongepowered.common.event.listener.PlaceListener_BuildPermListener_onPlayerPlacesBlock196.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:340)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141)
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:583)
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:503)
	at org.spongepowered.common.event.tracking.phase.block.PistonMovingPhaseState.unwind(PistonMovingPhaseState.java:58)
	at org.spongepowered.common.event.tracking.phase.block.BlockPhase.unwind(BlockPhase.java:73)
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192)
	at net.minecraft.block.BlockPistonBase.handler$onDoMoveReturn$zbh000(BlockPistonBase.java:117)
	at net.minecraft.block.BlockPistonBase.func_176319_a(BlockPistonBase.java:418)
	at net.minecraft.block.BlockPistonBase.func_189539_a(BlockPistonBase.java:196)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:458)
	at org.spongepowered.common.event.tracking.TrackingUtil.fireMinecraftBlockEvent(TrackingUtil.java:314)
	at net.minecraft.world.WorldServer.redirect$onFireBlockEvent$zjl000(WorldServer.java:768)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1217)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:233)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at com.arckenver.nations.DataHandler.getNation(DataHandler.java:140)
	at com.arckenver.nations.DataHandler.getPerm(DataHandler.java:207)
	at com.arckenver.nations.listener.BuildPermListener.lambda$null$59(BuildPermListener.java:31)
	at com.arckenver.nations.listener.BuildPermListener$$Lambda$1020/1869006253.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.arckenver.nations.listener.BuildPermListener.lambda$onPlayerPlacesBlock$60(BuildPermListener.java:30)
	at com.arckenver.nations.listener.BuildPermListener$$Lambda$1019/611640378.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.arckenver.nations.listener.BuildPermListener.onPlayerPlacesBlock(BuildPermListener.java:30)
	at org.spongepowered.common.event.listener.PlaceListener_BuildPermListener_onPlayerPlacesBlock196.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:340)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141)
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:583)
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:503)
	at org.spongepowered.common.event.tracking.phase.block.PistonMovingPhaseState.unwind(PistonMovingPhaseState.java:58)
	at org.spongepowered.common.event.tracking.phase.block.BlockPhase.unwind(BlockPhase.java:73)
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192)
	at net.minecraft.block.BlockPistonBase.handler$onDoMoveReturn$zbh000(BlockPistonBase.java:117)
	at net.minecraft.block.BlockPistonBase.func_176319_a(BlockPistonBase.java:418)
	at net.minecraft.block.BlockPistonBase.func_189539_a(BlockPistonBase.java:196)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:458)
	at org.spongepowered.common.event.tracking.TrackingUtil.fireMinecraftBlockEvent(TrackingUtil.java:314)
	at net.minecraft.world.WorldServer.redirect$onFireBlockEvent$zjl000(WorldServer.java:768)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1217)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:233)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
```

**Comment by TheoKah** [comment] 2016-12-21 02:30
Can you give us steps to reproduce the problem?
Is it using spongevanilla or songeforge?

**Comment by GershonR** [comment] 2016-12-22 21:19
This is using SpongeForge, I believe its done by either players not inside a nation and either placing or using pistons or somehow by members in a nation spamming them or something along those lines. I currently blacklisted pistons on my server to prevent the crash from happening.

**Comment by TheoKah** [comment] 2017-01-10 22:48
I were unable to reproduce it on my test server. Also using nation in 4 public servers and none of them had the problem in months.

Closing this issue as I were unable to reproduce it. Once PR #77 is merged and Nation released, can you try again and reopen with a new crashlog if the error is still there?

**Closed as completed by TheoKah** 2017-01-10 22:48 UTC
